# permissions for end users to view fridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fridge-viewer-role
rules:
- apiGroups:
  - iot.ctison.dev
  resources:
  - fridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iot.ctison.dev
  resources:
  - fridges/status
  verbs:
  - get
