# permissions for end users to edit fridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fridge-editor-role
rules:
- apiGroups:
  - iot.ctison.dev
  resources:
  - fridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.ctison.dev
  resources:
  - fridges/status
  verbs:
  - get
